# Generated by Django 3.1.3 on 2020-11-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_crud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
